ass1/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
	url(r'^doodle/', include('doodle.urls', namespace="doodle")),
    url(r'^admin/', include(admin.site.urls)),
)

doodle/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create/$', views.new_meeting, name='new_meeting'), 
    url(r'^room/(?P<meeting_id>[0-9]+)/$', views.room, name='room'), 
    url(r'^(?P<meeting_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<meeting_id>[0-9]+)/results/$', views.results, name='results'),
    # # ex: /polls/5/vote/
    url(r'^(?P<meeting_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

doodle/models.py
from django.db import models

class Mdate(models.Model):
    mdate = models.DateTimeField('meeting date', auto_now_add=True)

class Room(models.Model):
    location = models.CharField(max_length=200)
    capasity = models.IntegerField(default=10)
    
class Meeting (models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    r_votes = models.IntegerField(default=5)
    mdate = models.ForeignKey(Mdate, blank=True, null=True)
    room = models.ForeignKey(Room, blank=True, null=True)

class Choice(models.Model):
    meeting = models.ForeignKey(Meeting)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    choice_date = models.DateTimeField()

doodle/forms.py
from django import forms
from .models import Meeting, Choice, Mdate, Room

#form used for creating new meeting
class MeetingForm(forms.Form):
    title = forms.CharField(label="Title of Meeting")
    r_votes = forms.IntegerField(label="Required Votes to set time")

#form used for assigning room to meeting
class RoomForm(forms.Form):
	room = forms.ModelChoiceField(queryset = Room.objects.all() )

doodle/views.py
from django.utils import timezone
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from doodle.forms import *
from django.shortcuts import * 
from .models import Meeting, Choice, Mdate, Room

#index method displas all list of created meetings 
def index(request):
    latest_meeting_list = Meeting.objects.order_by('-pub_date')[:5]
    context = {'latest_meeting_list': latest_meeting_list}
    return render(request, 'doodle/index.html', context)

# display meeting details, if date is not selected it will lead you to vote for date
# if date is decided it will leads you to chose room 
# if room is selected it will leads you to result, will all details of meeting with time and room no
def detail(request, meeting_id):
    meeting =  get_object_or_404(Meeting, pk=meeting_id)
    mdate = Mdate.objects.filter(meeting = meeting)
    room = Room.objects.filter(meeting = meeting)
    if (room.exists()):
        return HttpResponseRedirect(reverse('doodle:results', args=(meeting.id,)))
    elif ( mdate.exists()): 
        return HttpResponseRedirect(reverse('doodle:room', args=(meeting.id,)))
    else:
        return render(request, 'doodle/detail.html', {'meeting': meeting})

#this method handles assigning room to the meeting after chosing date for meeting
def room(request, meeting_id):
    if request.method == "POST":
        form = RoomForm(request.POST)
        if(form.is_valid()):
            room = get_object_or_404(Room, pk=request.POST['room'])
            meeting = get_object_or_404(Meeting, pk=meeting_id)
            room.meeting_set.add(meeting)
            room.save()
            meeting.room = room
            meeting.save()
            message = "Congrats!! Room has been assigned"
            return HttpResponseRedirect(reverse('doodle:results', args=(meeting.id,)))
        else:
            message = "Room is not assigned"
        return render_to_response('doodle/room.html',
                {'success': message},
                context_instance=RequestContext(request))
    else:
        return render_to_response('doodle/room.html',
                {'form':RoomForm()},
                context_instance=RequestContext(request, { 'meeting_id': meeting_id}))

# this method is used to create new meetings
def new_meeting(request):
    if request.method == "POST":
        form = MeetingForm(request.POST)
        
        if(form.is_valid()):
            new_meeting = Meeting(title =  request.POST['title'], r_votes= request.POST['r_votes'], pub_date= timezone.now())
            new_meeting.save()
            # adding there default option with one day difference of date
            new_meeting.choice_set.create(choice_text='Prefered Option', choice_date= (timezone.now() + timezone.timedelta(days=1)))
            new_meeting.choice_set.create(choice_text='Second Option', choice_date=( timezone.now() + timezone.timedelta(days=2)))
            new_meeting.choice_set.create(choice_text='Last Option', choice_date= ( timezone.now() + timezone.timedelta(days=3)))

            message = "Congrats!! New Meeting has been created."
        else:
            message = "sorry something went wrong"
        return render_to_response('doodle/new.html',
                {'success': message},
                context_instance=RequestContext(request))
    else:
        return render_to_response('doodle/new.html',
                {'form':MeetingForm()},
                context_instance=RequestContext(request))

#this method is used to vote for any choice 
def vote(request, meeting_id):
    p = get_object_or_404(Meeting, pk=meeting_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'doodle/detail.html', {
            'meeting': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        if selected_choice.votes >= selected_choice.meeting.r_votes :
        	mdate = Mdate(mdate= selected_choice.choice_date)
        	mdate.save()
        	mdate.meeting_set.add(selected_choice.meeting)
        	mdate.save()
        	selected_choice.meeting.mdate = mdate
        	selected_choice.meeting.save()
        return HttpResponseRedirect(reverse('doodle:results', args=(p.id,)))

#this method shows all status of meeting at any stage 
def results(request, meeting_id):
    meeting = get_object_or_404(Meeting, pk=meeting_id)
    mdate = Mdate.objects.filter(meeting = meeting)
    room = Room.objects.filter(meeting = meeting)
    can_vote = mdate.exists()
    has_room = room.exists()
    # import pdb; pdb.set_trace()
    if can_vote :
        mdate=mdate[0]
    if has_room :
        room = room[0]
    return render(request, 'doodle/result.html', {'meeting': meeting, 'mdate': mdate, 'room': room, 'can_vote': can_vote, 'has_room': has_room})

doodle/templates/doodle/detail.html
<h1>Vote for meeting timing choice</h1>
<h2>Meeting Title: {{ meeting.title }}</h2>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'doodle:vote' meeting.id %}" method="post">
{% csrf_token %}
{% for choice in meeting.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }} : {{ choice.choice_date }} </label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

<div></br></br>
	<p> Go to <a href="{% url 'doodle:index'%}">Home</a> to View all meetings List </p>
</div>

doodle/templates/doodle/index.html
<h1>Welcome to Doodle Home</h1>
<h4>List of all meeting agendas</h4>
{% if latest_meeting_list %}
    <ul>
    {% for metting in latest_meeting_list %}
       <li><a href="{% url 'doodle:detail' metting.id %}">{{ metting.title }} Decided Meeting date : </a></li>
    {% endfor %} 
    </ul>
{% else %}
    <p>No Meetings are available.</p>
{% endif %}
<a href="{% url 'doodle:new_meeting' %}">Create new Meeting</a>

doodle/templates/doodle/new.html
<h1>Create New meeting</h1>
{% if success %} 
<div></br></br>
	<p> {{success}}</p>
</div>	
{%else %}

<form action="/doodle/create/" method="post">{% csrf_token %}
  {% for field in form %}
  <div>{{ field.label_tag }} {{ field }}</div>
  {% endfor %}
  <input type="submit" value="Create Meeting" />
</form>

{%endif%}
<div></br></br>
	<p> Go to <a href="{% url 'doodle:index'%}">Home</a> to View all meetings List </p>

</div>

doodle/templates/doodle/result.html
<h1>Meeting Agenda : {{ meeting.title }}</h1>

{%if can_vote %}
    <h4>Chosen Date: </h4> {{mdate.mdate}} 
    {%if has_room%}
     <h4>Selected Room </h4>
        <h5> Location:{{room.location}} </h5> 
        <h5> Capacity:  {{room.capasity}} </h5>
    {%else %}
        <p> Now you can <a href="/doodle/room/{{meeting.id}}/">Chose a Room </a>  </p>
    {%endif%}
{% else %}
	<ul>
		{% for choice in meeting.choice_set.all %}
		    <li>{{ choice.choice_text }} : {{ choice.choice_date }}  >> -- {{ choice.votes }}  vote{{ choice.votes|pluralize }}</li>
		{% endfor %}
	</ul>
	<a href="{% url 'doodle:detail' meeting.id %}">Vote again?</a>
{%endif%}

<div></br></br>
	<p> Go to <a href="{% url 'doodle:index'%}">Home</a> to View all meetings List </p>
</div>

doodle/templates/doodle/room.html
<h1>Select Room</h1>
<p>
	<h3>Time has allready been choosen by voting for meeting id : {{meeting_id}} </h3>
</p>
{% if success %} 
<div></br></br>
	<p> {{success}}</p>
</div>	
{%else %}

<form action= "/doodle/room/{{meeting_id}}/"  method="post">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Create Meeting" />
</form>

{%endif%}

<div></br></br>
	<p> Go to <a href="{% url 'doodle:index'%}">Home</a> to View all meetings List </p>

</div>